import json

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from ezi.views import ModelCrudApiView

from Servers.common import utils as common_utils
from Servers.common.api_remotes.models import ClientServer

@method_decorator(login_required, name="dispatch")
class ClientServerCrudApiView(ModelCrudApiView):

    model = ClientServer

    allowed_methods = ("PUT")

    def create_object(self):
        """
        Override of ezi.views.ModelCrudApiView.create_object. This method takes
        input from self.request.PUT and creates an instance of self.model from
        that input.

        This override takes the client_server input and sends it to
        'ClientServer.objects.create()'.

        The data in self.request.PUT is expected to have a key named auth_user
        that contains the json for the user to be created or updated. This json
        must be in the format generated by AuthUser.json().

        Returns the model object created from the json representing the user.
        """
        PUT = common_utils.get_PUT_data(self.request)
        auth_user_data = json.loads(PUT["client_server"])
        return self.model.objects.create(**auth_user_data)
