# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='fingerprint_image',
            field=models.ImageField(default=None, upload_to='Images/'),
            preserve_default=False,
        ),
    ]
