# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0002_authuser_fingerprint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='index_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='fingerprint_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
